use zoo;
db.dropDatabase();

db.animals.insertMany([
    {“name”: “Pigeon Guillemot”,
    “latin_name”: “Cepphus columba”,
    “animal_type”: “Bird”,
    “active_time”: “Diurnal”,
    “length_min”: “0.88",
    “length_max”: “1.2",
    “weight_min”: “1",
    “weight_max”: “1.1",
    “lifespan”: “15",
    “habitat”: “Ocean and rocky coastal cliffs”,
    “diet”: “Fish and aquatic invertebrates”,
    “geo_range”: “Arctic and Pacific oceans and coasts of North America and Asia”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/1/1b/Pigeon_guillemot.jpg”,
    “id”: 135
    },
    {“name”: “Burmese Brown Mountain Tortoise”,
    “latin_name”: “Manouria emys emys”,
    “animal_type”: “Reptile”,
    “active_time”: “Diurnal”,
    “length_min”: “1.5”,
    “length_max”: “2”,
    “weight_min”: “70”,
    “weight_max”: “80”,
    “lifespan”: “60”,
    “habitat”: “Forest”,
    “diet”: “Grass, leaves, fungi, and fruit”,
    “geo_range”: “Southeastern Asia”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/6/69/Manouria-emys-asian-forest-tortoise.jpg”,
    “id”: 48
    },
    {“name”: “Two-toed Amphiuma”,
    “latin_name”: “Amphiuma means”,
    “animal_type”: “Amphibian”,
    “active_time”: “Nocturnal”,
    “length_min”: “3",
    “length_max”: “4",
    “weight_min”: “0.09",
    “weight_max”: “2.3",
    “lifespan”: “20",
    “habitat”: “Swamps, ponds and other still waters”,
    “diet”: “Fish, frogs, crayfish, and small snakes”,
    “geo_range”: “Southeastern United States”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/4/44/Amphiuma_%28two-toed%29.jpg”,
    “id”: 178
    },
    {“name”: “Dyeing Poison Dart Frog”,
    “latin_name”: “Dendrobatus tinctorius”,
    “animal_type”: “Amphibian”,
    “active_time”: “Diurnal”,
    “length_min”: “0.13”,
    “length_max”: “0.2”,
    “weight_min”: “0.01”,
    “weight_max”: “0.01”,
    “lifespan”: “10”,
    “habitat”: “Tropical rainforest”,
    “diet”: “Insects, spiders, and other small invertebrates”,
    “geo_range”: “South America”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/1/17/Dendrobates_tinctorius_-_Karlsruhe_Zoo_05.jpg”,
    “id”: 63
    },
    {“name”: “Pallas’s Cat”,
    “latin_name”: “Octocolobus manul”,
    “animal_type”: “Mammal”,
    “active_time”: “Nocturnal”,
    “length_min”: “1.5",
    “length_max”: “2",
    “weight_min”: “6.5",
    “weight_max”: “11",
    “lifespan”: “8",
    “habitat”: “Mountain regions, including grassland, woodland, and semi-desert”,
    “diet”: “Pikas, hares, and small rodents such as gerbils, voles, and young marmots”,
    “geo_range”: “Central Asia”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/d/d6/Manoel.jpg”,
    “id”: 131
    },
    {“name”: “Potto”,
    “latin_name”: “Perodictus potto”,
    “animal_type”: “Mammal”,
    “active_time”: “Nocturnal”,
    “length_min”: “1”,
    “length_max”: “1.3”,
    “weight_min”: “1.7”,
    “weight_max”: “3.7”,
    “lifespan”: “25”,
    “habitat”: “Tropical forest”,
    “diet”: “Fruit, insects and other small animals”,
    “geo_range”: “Western and Central Africa”,
    “image_link”: “https://static.wikia.nocookie.net/animals/images/6/67/Potto.jpg”,
    “id”: 139
    },
    {“name”: “Rough Green Snake”,
    “latin_name”: “Opheodrys aestivus”,
    “animal_type”: “Reptile”,
    “active_time”: “Diurnal”,
    “length_min”: “1.83",
    “length_max”: “2.67",
    “weight_min”: “0.02",
    “weight_max”: “0.12",
    “lifespan”: “10",
    “habitat”: “Moist woodland”,
    “diet”: “Insects and spiders”,
    “geo_range”: “Southeastern United States”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/b/bd/Rough_Green_Snake.jpg”,
    “id”: 153
    },
    {“name”: “Red-eared Slider”,
    “latin_name”: “Trachemys scripta elegans”,
    “animal_type”: “Reptile”,
    “active_time”: “Diurnal”,
    “length_min”: “0.42”,
    “length_max”: “0.92”,
    “weight_min”: “1.5”,
    “weight_max”: “2”,
    “lifespan”: “20”,
    “habitat”: “Freshwater ponds and streams”,
    “diet”: “Fish, mollusks, and insects”,
    “geo_range”: “Southern and Midwestern United States”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/9/96/RedEaredSlider05.jpg”,
    “id”: 149
    },
    {“name”: “Jamaican Boa”,
    “latin_name”: “Chilabothrus subflavus”,
    “animal_type”: “Reptile”,
    “active_time”: “Nocturnal”,
    “length_min”: “4.5",
    “length_max”: “7.5",
    “weight_min”: “9",
    “weight_max”: “11",
    “lifespan”: “24",
    “habitat”: “Tropical forest”,
    “diet”: “Mammals and birds”,
    “geo_range”: “Jamaica”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/d/d2/Epicrates_subflavus.jpg”,
    “id”: 95
    },
    {“name”: “Aardvark”,
    “latin_name”: “Orycteropus afer”,
    “animal_type”: “Mammal”,
    “active_time”: “Nocturnal”,
    “length_min”: “3.4”,
    “length_max”: “4.2”,
    “weight_min”: “88”,
    “weight_max”: “143”,
    “lifespan”: “12”,
    “habitat”: “Woodland, scrubland, and grassland”,
    “diet”: “Ants and termites”,
    “geo_range”: “Central and Southern Africa”,
    “image_link”: “https://upload.wikimedia.org/wikipedia/commons/6/67/SanWild17.jpg”,
    “id”: 1
    }
    ]);
